### ISSUE TITLE
This repo could use a better README

### ISSUE THREAD

**Issue by thundergolfer** [jbelmont/rust-vs-go-cli-comparison#1]
Hey, 

Came across this project while searching for info on "Rust vs. Go CLIs", and this looks like it has a lot of exploration in it which is great. 

The `README.md` is just the project title though. I think it could use: 

* Repo structure information
* Installation instructions
* Summary of insights gained from your explanation
* Recommendations based on your insights

**Comment by jbelmont** [comment]
Hello,

Thank you @thundergolfer for taking a look and providing suggestions, yes I should totally provide a better *README.md* for this project. I did this for an all things open talk and then a meetup talk event at https://slides.com/jbelmont80/rust-2#/. I will update the README.md with your suggestions as they are very good.

All the best,

Jean-Marcel

**Comment by jbelmont** [comment]
I have updated the README.md with your suggestions let me know if it could be improved and thanks again!

**Comment by thundergolfer** [comment]
Bam! Nicely done. 🎉 

I'll dive into sometime when I get the chance to look at Rust again.

**Comment by jbelmont** [comment]
Great thank you!
